# Generated by Django 3.2.12 on 2022-04-05 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_No',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=500, unique=True)),
                ('receive_from', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField()),
                ('item_qty', models.IntegerField()),
                ('receipt_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptno', to='invoice.receipt_no')),
            ],
        ),
    ]
