# Generated by Django 3.2.12 on 2022-04-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_no',
            name='address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt_no',
            name='phone',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
