# Generated by Django 3.2.12 on 2022-04-05 12:14

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0003_receipt_no_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_no',
            name='user',
            field=models.ForeignKey(default=account.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
